name: Lint Markdown

on:
  workflow_dispatch:
  pull_request:

jobs:
  md-linter:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .markdownlint.json
